services:
  # Serviço do Banco de Dados da Aplicação (Quarkus)
  postgres-app:
    image: postgres:15-alpine
    container_name: postgres-app-ecommerce
    environment:
      POSTGRES_DB: ${APP_DB_NAME}
      POSTGRES_USER: ${APP_DB_USER}
      POSTGRES_PASSWORD: ${APP_DB_PASSWORD}
    ports:
      - "5432:5432"
    volumes:
      - pgdata-app:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  # Serviço do Banco de Dados do Keycloak
  postgres-keycloak:
    image: postgres:15-alpine
    container_name: postgres-keycloak-ecommerce
    environment:
      POSTGRES_DB: ${KC_DB_NAME}
      POSTGRES_USER: ${KC_DB_USER}
      POSTGRES_PASSWORD: ${KC_DB_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - pgdata-keycloak:/var/lib/postgresql/data
    networks:
      - ecommerce-network

  # Serviço do Keycloak
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak-ecommerce
    command: start-dev
    restart: unless-stopped
    environment:
      KC_DB: postgres
      KC_DB_URL: jdbc:postgresql://postgres-keycloak:5432/${KC_DB_NAME}
      KC_DB_USERNAME: ${KC_DB_USER}
      KC_DB_PASSWORD: ${KC_DB_PASSWORD}
      KEYCLOAK_ADMIN: ${KEYCLOAK_ADMIN}
      KEYCLOAK_ADMIN_PASSWORD: ${KEYCLOAK_ADMIN_PASSWORD}
    ports:
      - "8080:8080"
    depends_on:
      - postgres-keycloak
    networks:
      - ecommerce-network

  # Servidor de E-mail de Testes (Mailpit)
  # mailpit:
  #   image: axllent/mailpit:latest
  #   container_name: mailpit-ecommerce
  #   ports:
  #     - "1025:1025"
  #     - "8025:8025"
  #   networks:
  #     - ecommerce-network

  # Interface Visual do Banco de Dados (pgAdmin)
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin-ecommerce
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD}
    ports:
      - "8085:80"
    depends_on:
      - postgres-app
      - postgres-keycloak
    networks:
      - ecommerce-network

networks:
  ecommerce-network:
    driver: bridge

volumes:
  pgdata-app:
  pgdata-keycloak: