# configuracao do bd
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=kuasys
quarkus.datasource.password=123456
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/kuasys_db

# keycloak ocupa a porta padrão
quarkus.http.port=8081

# desabilitar o docker 
quarkus.devservices.enabled=false

# parte aplicação parte keycloak...
quarkus.hibernate-orm.database.default-schema=public 
quarkus.hibernate-orm.database.generation=drop-and-create
# quarkus.hibernate-orm.database.generation=none
# quarkus.hibernate-orm.database.generation=update
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true

# Keycloak Authorization Configuration
quarkus.keycloak.policy-enforcer.enable=true
quarkus.oidc.token.audience=backend-api

# o keycloak rodando em uma rede diferente (docker) precisa disso...
quarkus.oidc.token.issuer=http://localhost:8080/realms/realm-kuasys

quarkus.oidc.auth-server-url=http://localhost:8080/realms/realm-kuasys
quarkus.oidc.client-id=backend-api
quarkus.oidc.credentials.secret=Ma7ZNjU5uc9nqLolt6vIaoSEEfTHqDAK
quarkus.oidc.tls.verification=none 
quarkus.oidc.application-type=service

# Faz com que TODOS os seus endpoints comecem com /api (Ex: /api/quadrinhos)
quarkus.http.root-path=api

# Role mapping from Keycloak
quarkus.oidc.roles.role-claim-path=realm_access.roles

quarkus.keycloak.policy-enforcer.enforcement-mode=PERMISSIVE

# Ativa o fluxo de autenticação do OAuth2 no Swagger UI
quarkus.smallrye-openapi.security-scheme=oauth2
quarkus.smallrye-openapi.oauth2-auth-url=http://localhost:8080/realms/realm-kuasys/protocol/openid-connect/auth
quarkus.smallrye-openapi.oauth2-token-url=http://localhost:8080/realms/realm-kuasys/protocol/openid-connect/token


# Força o Quarkus a validar o token localmente usando JWT, em vez de perguntar via Opaque Token
quarkus.oidc.token-path-id-token-unwrapped=true
quarkus.oidc.authentication.verify-access-token=true

# aparentemente um bug no keycloak causa a necessidade disso
quarkus.oidc.authentication.internal-id-token-verification=false

# 1. Ativa o CORS globalmente
quarkus.http.cors=true
quarkus.http.cors.origins=http://localhost:3000
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type

