#################################################################
#                 Configuração do banco de dados                #
#################################################################
quarkus.datasource.db-kind=postgresql
quarkus.datasource.username=kuasys
quarkus.datasource.password=123456
quarkus.datasource.jdbc.url=jdbc:postgresql://localhost:5432/kuasys_db
# parte aplicação parte keycloak...
quarkus.hibernate-orm.database.default-schema=public
quarkus.hibernate-orm.database.generation=drop-and-create
quarkus.hibernate-orm.log.sql=true
quarkus.hibernate-orm.log.bind-parameters=true
# keycloak ocupa a porta padrão
quarkus.http.port=8081
# desabilitar o docker 
quarkus.devservices.enabled=false
#################################################################
#                 Configuração do banco de dados                #
#################################################################
quarkus.keycloak.policy-enforcer.enable=false
quarkus.oidc.token.audience=backend-api
# o keycloak rodando em uma rede diferente (docker) precisa disso...
quarkus.oidc.token.issuer=http://localhost:8080/realms/realm-kuasys
quarkus.oidc.auth-server-url=http://localhost:8080/realms/realm-kuasys
quarkus.oidc.client-id=backend-api
quarkus.oidc.credentials.secret=Ma7ZNjU5uc9nqLolt6vIaoSEEfTHqDAK
quarkus.oidc.tls.verification=none
quarkus.oidc.application-type=service
# Faz com que TODOS os seus endpoints comecem com /api (Ex: /api/quadrinhos)
quarkus.http.root-path=api
# Role mapping from Keycloak
quarkus.oidc.roles.role-claim-path=realm_access/roles
quarkus.keycloak.policy-enforcer.enforcement-mode=PERMISSIVE
# Força o Quarkus a validar o token localmente usando JWT, em vez de perguntar via Opaque Token
quarkus.oidc.token-path-id-token-unwrapped=true
quarkus.oidc.authentication.verify-access-token=true
# aparentemente um bug no keycloak causa a necessidade disso
quarkus.oidc.authentication.internal-id-token-verification=false
#################################################################
#                 Configuração do Keycloak                      #
#################################################################
quarkus.keycloak.admin-client.server-url=http://localhost:8080/
quarkus.keycloak.admin-client.realm=master
quarkus.keycloak.admin-client.client-id=admin-cli
quarkus.keycloak.admin-client.username=admin
quarkus.keycloak.admin-client.password=admin
#################################################################
#                 Configuração do CORS                          #
#################################################################
quarkus.http.cors.enabled=true
quarkus.http.cors.origins=*
quarkus.http.cors.methods=GET,POST,PUT,DELETE,OPTIONS
quarkus.http.cors.headers=accept,authorization,content-type,X-Cart-Token
# Ignora a segurança do Keycloak para a vitrine e imagens públicas
quarkus.keycloak.policy-enforcer.paths.vitrine.path=/vitrine/*
quarkus.keycloak.policy-enforcer.paths.vitrine.enforcement-mode=DISABLED
quarkus.keycloak.policy-enforcer.paths.imagens.path=/imagens/*
quarkus.keycloak.policy-enforcer.paths.imagens.enforcement-mode=DISABLED
